language: node_js
node_js: "11"
cache: yarn
matrix:
  include:
    - os: linux
    - os: osx
install: yarn
script: yarn dist
deploy:
  skip_cleanup: true
  provider: script
  script: yarn release 
  on: master
